/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Saqib Ali (https://sketchfab.com/Syed.Saqib.Kazmi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-colorful-sci-fi-skybox-1e67ffe2c1974cc3b6882f413e45ab02
Title: Free - Colorful Sci Fi Skybox
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from "../assets/3d/sk.glb"
import { useFrame } from '@react-three/fiber'
const Skya=({isRotating})=> {
  
  const skref=useRef()
  const sk=useGLTF(scene)
  useFrame((_,delta)=>{
    if(isRotating)
    {
      skref.current.rotation.y+=0.15 * delta
    }
      })
  return (
  
    <mesh ref={skref}>
        <primitive object={sk.scene} />
    </mesh>
  )
}

export default Skya